### ISSUE TITLE
Master TODO List

### ISSUE THREAD

**Issue by kevalpithadiya** [databasedIISc/databasediisc.github.io#26]
# Website Master TODO List

## Webpages and Implementations
- [ ] Implement major event list to use Airtable for dynamic updation
- [ ] Add webpage for Math Problem Solving sessions to share Problem and Solution PDFs (through Airtable)
- [ ] Work on adding SEO & OG tags to all pages

## Devops
- [ ] Integrate [**Deploy PR Preview**](https://github.com/marketplace/actions/deploy-pr-preview)
- [ ] Create a base template for pages to make it easier to add new pages
